#ifndef XYBASEMANAGEMENT_GLOBAL_H
#define XYBASEMANAGEMENT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef XYBASEMANAGEMENT_LIB
# define XYBASEMANAGEMENT_EXPORT Q_DECL_EXPORT
#else
# define XYBASEMANAGEMENT_EXPORT Q_DECL_IMPORT
#endif

#endif // XYBASEMANAGEMENT_GLOBAL_H
