#ifndef PROGRESSBARMANAGER_GLOBAL_H
#define PROGRESSBARMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROGRESSBARMANAGER_LIB
# define PROGRESSBARMANAGER_EXPORT Q_DECL_EXPORT
#else
# define PROGRESSBARMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // PROGRESSBARMANAGER_GLOBAL_H
