#ifndef XYALARMMANAGEMENT_GLOBAL_H
#define XYALARMMANAGEMENT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef XYALARMMANAGEMENT_LIB
# define XYALARMMANAGEMENT_EXPORT Q_DECL_EXPORT
#else
# define XYALARMMANAGEMENT_EXPORT Q_DECL_IMPORT
#endif

#endif // XYALARMMANAGEMENT_GLOBAL_H
