#ifndef XYREPORTCENTER_GLOBAL_H
#define XYREPORTCENTER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef XYREPORTCENTER_LIB
# define XYREPORTCENTER_EXPORT Q_DECL_EXPORT
#else
# define XYREPORTCENTER_EXPORT Q_DECL_IMPORT
#endif

#endif // XYREPORTCENTER_GLOBAL_H
